# inherit_from: .rubocop_todo.yml
AllCops:
 Include:
   - '**/Rakefile'
   - '**/config.ru'
 Exclude:
   - 'bin/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'res/**/*'
   - 'script/**/*'
   - !ruby/regexp /old_and_unused\.rb$/
 UseCache: true
Rails:
 Enabled: true
Metrics/LineLength:
 Max: 120
Style/Documentation:
 Enabled: false
